# Generated by Django 5.1.5 on 2025-02-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_alter_student_branch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="branch",
            field=models.CharField(max_length=50),
        ),
    ]
