# Generated by Django 5.1.7 on 2025-04-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_rename_payment_orderproduct_payment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                    ("Accepted", "Accepted"),
                    ("New", "New"),
                ],
                default="New",
                max_length=10,
            ),
        ),
    ]
