# Generated by Django 5.1.7 on 2025-04-03 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_userprofile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="profile_pic",
            new_name="profile_picture",
        ),
    ]
